-- Obsolete: kept only to avoid old references breaking.
-- Use RESEARCH_UPGRADE.sql for schema alignment.
-- Authorization hardening should be handled separately with Supabase Auth/RLS or Edge Functions.
